// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohtzcaapviofbbjvlma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaHR6Y2FhcHZpb2ZiYmp2bG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTU2NTMsImV4cCI6MjA3MDI3MTY1M30.ig3bu7qMWdO9HhytQmqXsy2i1xm9PUyV4mBcSUNTg_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});